CREATE TABLE `authors` (
	`id` text PRIMARY KEY NOT NULL,
	`username` text DEFAULT '' NOT NULL,
	`passwordHash` text,
	`displayName` text,
	`email` text,
	`bio` text,
	`avatarUrl` text,
	`walletAddress` text,
	`publicKey` text,
	`privateKeyEncrypted` text,
	`totalWorks` integer DEFAULT 0 NOT NULL,
	`totalWords` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`preferences` text,
	`lastActiveAt` integer,
	`createdAt` integer DEFAULT 0 NOT NULL,
	`updatedAt` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `chapters` (
	`id` text PRIMARY KEY NOT NULL,
	`workId` text DEFAULT '' NOT NULL,
	`parentId` text,
	`level` integer DEFAULT 1 NOT NULL,
	`orderIndex` integer DEFAULT 0 NOT NULL,
	`title` text DEFAULT '' NOT NULL,
	`subtitle` text,
	`description` text,
	`type` text DEFAULT 'chapter' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`wordCount` integer DEFAULT 0 NOT NULL,
	`characterCount` integer DEFAULT 0 NOT NULL,
	`contentCount` integer DEFAULT 0 NOT NULL,
	`childChapterCount` integer DEFAULT 0 NOT NULL,
	`progressPercentage` real DEFAULT 0 NOT NULL,
	`targetWords` integer,
	`authorId` text DEFAULT '' NOT NULL,
	`storyTimelineStart` text,
	`storyTimelineEnd` text,
	`tags` text,
	`blockchainHash` text,
	`isPublic` integer DEFAULT false NOT NULL,
	`publishedAt` integer,
	`metadata` text,
	`createdAt` integer DEFAULT 0 NOT NULL,
	`updatedAt` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `collaborativeDocuments` (
	`id` text PRIMARY KEY NOT NULL,
	`contentId` text DEFAULT '' NOT NULL,
	`workId` text DEFAULT '' NOT NULL,
	`documentType` text DEFAULT 'text' NOT NULL,
	`yjsState` text,
	`stateVector` text,
	`maxConnections` integer DEFAULT 10 NOT NULL,
	`lastSyncAt` integer,
	`createdAt` integer DEFAULT 0 NOT NULL,
	`updatedAt` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `contentVersions` (
	`id` text PRIMARY KEY NOT NULL,
	`contentId` text DEFAULT '' NOT NULL,
	`contentJson` text DEFAULT '' NOT NULL,
	`contentHtml` text,
	`contentText` text,
	`wordCount` integer DEFAULT 0 NOT NULL,
	`characterCount` integer DEFAULT 0 NOT NULL,
	`versionNumber` integer DEFAULT 1 NOT NULL,
	`changeSummary` text,
	`authorId` text DEFAULT '' NOT NULL,
	`blockchainHash` text,
	`createdAt` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `contents` (
	`id` text PRIMARY KEY NOT NULL,
	`workId` text DEFAULT '' NOT NULL,
	`chapterId` text,
	`orderIndex` integer DEFAULT 0 NOT NULL,
	`title` text,
	`type` text DEFAULT 'text' NOT NULL,
	`contentJson` text,
	`wordCount` integer DEFAULT 0 NOT NULL,
	`characterCount` integer DEFAULT 0 NOT NULL,
	`paragraphCount` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`authorId` text DEFAULT '' NOT NULL,
	`isCollaborative` integer DEFAULT false NOT NULL,
	`contributors` text,
	`storyTimeline` text,
	`charactersInvolved` text,
	`location` text,
	`sceneDescription` text,
	`tags` text,
	`emotionTone` text,
	`importanceLevel` integer DEFAULT 3 NOT NULL,
	`contentHash` text,
	`blockchainTimestamp` integer,
	`copyrightStatus` text DEFAULT 'draft' NOT NULL,
	`isPublic` integer DEFAULT false NOT NULL,
	`publishedAt` integer,
	`writingDuration` integer DEFAULT 0 NOT NULL,
	`lastEditedAt` integer DEFAULT 0 NOT NULL,
	`lastEditorId` text DEFAULT '' NOT NULL,
	`notes` text,
	`metadata` text,
	`createdAt` integer DEFAULT 0 NOT NULL,
	`updatedAt` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `works` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text DEFAULT '' NOT NULL,
	`subtitle` text,
	`description` text,
	`coverImageUrl` text,
	`genre` text,
	`tags` text,
	`authorId` text DEFAULT '' NOT NULL,
	`collaborationMode` text DEFAULT 'solo' NOT NULL,
	`collaborators` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`progressPercentage` real DEFAULT 0 NOT NULL,
	`totalWords` integer DEFAULT 0 NOT NULL,
	`totalCharacters` integer DEFAULT 0 NOT NULL,
	`chapterCount` integer DEFAULT 0 NOT NULL,
	`targetWords` integer,
	`targetCompletionDate` integer,
	`blockchainHash` text,
	`nftTokenId` text,
	`nftContractAddress` text,
	`copyrightHash` text,
	`isPublic` integer DEFAULT false NOT NULL,
	`licenseType` text DEFAULT 'all_rights_reserved' NOT NULL,
	`publishedAt` integer,
	`metadata` text,
	`createdAt` integer DEFAULT 0 NOT NULL,
	`updatedAt` integer DEFAULT 0 NOT NULL
);
